version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        image: nginx:0.1.0
        ports:
            - '80:80'
        networks:
            - webnet
        depends_on:
            - flask-scholarly
    flask-scholarly:
        build:
            context: .
            dockerfile: Dockerfile-flask-scholarly
        image: flask-scholarly:0.1.0
        networks:
            webnet:
                aliases:
                    - flask-scholarly
networks:
    webnet:
